services:
  model-export-example:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8888:8888" # Jypyter inside the container
    restart: unless-stopped
    # Set the user and group ID to match the host, so that files created in the container are owned by the host user
    # default to 1000:1000 if not set, this is the default for the first user on most Linux systems
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      - HOME=/app
    working_dir: "/app"
    command: python3 -m jupyter lab --ip 0.0.0.0 --port 8888
    shm_size: "2gb" # PyTorch shared memory